// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RemainderBot.Core.DataLayer.Context;

namespace RemainderBot.Core.Migrations
{
    [DbContext(typeof(RemainderContext))]
    [Migration("20200414134059_DoingNothing")]
    partial class DoingNothing
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RemainderBot.Core.DataLayer.Context.Notes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MainContent")
                        .IsRequired();

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("RemainderBot.Core.DataLayer.Context.NotesTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("NotesId");

                    b.Property<long?>("TagsId");

                    b.HasKey("Id");

                    b.HasIndex("NotesId");

                    b.HasIndex("TagsId");

                    b.ToTable("NotesTag");
                });

            modelBuilder.Entity("RemainderBot.Core.DataLayer.Context.Remainder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Remainder");
                });

            modelBuilder.Entity("RemainderBot.Core.DataLayer.Context.Tags", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.Property<long?>("RemainderId");

                    b.HasKey("Id");

                    b.HasIndex("RemainderId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("RemainderBot.Core.DataLayer.Context.NotesTag", b =>
                {
                    b.HasOne("RemainderBot.Core.DataLayer.Context.Notes")
                        .WithMany("Tags")
                        .HasForeignKey("NotesId");

                    b.HasOne("RemainderBot.Core.DataLayer.Context.Tags", "Tags")
                        .WithMany()
                        .HasForeignKey("TagsId");
                });

            modelBuilder.Entity("RemainderBot.Core.DataLayer.Context.Tags", b =>
                {
                    b.HasOne("RemainderBot.Core.DataLayer.Context.Remainder", "Remainder")
                        .WithMany()
                        .HasForeignKey("RemainderId");
                });
#pragma warning restore 612, 618
        }
    }
}
